### ISSUE TITLE
Add Paper Request

### ISSUE THREAD

**Issue by Ruiyang-061X** [purshow/Awesome-LVLM-Hallucination#2]
Dear Purshow,

Thank you for your valuable effort in curating research on LVLM hallucination! Your commentary on these papers is highly insightful!

We have recently released our latest work: "VL-Uncertainty: Detecting Hallucination in Large Vision-Language Models via Uncertainty Estimation".

- Paper Link: https://arxiv.org/abs/2411.11919
- Website: https://vl-uncertainty.github.io/
- Code: https://github.com/Ruiyang-061X/VL-Uncertainty

I was wondering if you could kindly consider adding our paper to your excellent repository. Thank you once again for your invaluable contributions to this field!

Best regards,
Ruiyang

**Comment by Purshow** [comment]
of course! Thank you for your contribution!
